# Pandas Overview
*Gary Mitchell*

*03/16/2022*

Pandas is an important part of using Python for data science and/or machine learning. Modeled after R's Data Frame, the Pandas DataFrame provides us with sophisticated capabilities for maintaining and working with tables of data. This includes aggregating and summarizing, querying, merging, etc.

## The basics

Let's start with loading values from a .CSV file into a DataFrame. This might not seem like the basics (jumping right to reading a file), but it will allow us to take a look at a DataFrame and become familiar with it.

In [1]:
import numpy as np
import pandas as pd

# load the DataFrame from a .CSV file
statedat = pd.read_csv("statedat.csv")

# print out information about the DataFrame
print(statedat.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   abb         50 non-null     object
 1   name        50 non-null     object
 2   region      50 non-null     object
 3   area        50 non-null     int64
 4   center_x    50 non-null     float64
 5   center_y    50 non-null     float64
 6   income      50 non-null     int64
 7   illiteracy  50 non-null     float64
 8   life_exp    50 non-null     float64
 9   murder      50 non-null     float64
 10  hs_grad     50 non-null     float64
 11  frost       50 non-null     int64
 12  area.1      50 non-null     int64
dtypes: float64(6), int64(4), object(3)
memory usage: 5.2+ KB
None

As we see in the output above, the DataFrame's .info method gives us a detailed rundown of the DataFrame. For example, we can see that there are 50 rows (RangeIndex: 50 entries) and 13 columns. We see a directory of the 13 columns. For each column, we are given the name, how many non-null (i.e. non-missing) entries there are in that column, and the data type (dtype) of the column. The data types will be similar to those we've seen in Numpy Ndarrays.

This information is really nice to have immediately after reading a DataFrame, but it's also useful for understanding DataFrames. From this output, we see that DataFrames represent tables (i.e. a 2D representation of the data). Unlike a Numpy 2D array, the DataFrame allows for values to be of different data types, as long as all values within a *column* are of the same data type.

We can also take a look at some of the DataFrame's contents. The head function prints out the first *n* rows of the DataFrame (defaults to 5). Similarly, *tail* prints the last *n* rows. This is useful for gaining an intuitive understanding of the actual data.

In [2]:
statedat.head()

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
0,AL,Alabama,South,51609,-86.7509,32.5901,3624,2.1,69.05,15.1,41.3,20,50708
1,AK,Alaska,West,589757,-127.2500,49.2500,6315,1.5,69.31,11.3,66.7,152,566432
2,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417
3,AR,Arkansas,South,53104,-92.2992,34.7336,3378,1.9,70.66,10.1,39.9,65,51945
4,CA,California,West,158693,-119.7730,36.5341,5114,1.1,71.71,10.3,62.6,20,156361

In [3]:
statedat.tail()

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
45,VA,Virginia,South,40815,-78.2005,37.5630,4701,1.4,70.08,9.5,47.8,85,39780
46,WA,Washington,West,68192,-119.7460,47.4231,4864,0.6,71.72,4.3,63.5,32,66570
47,WV,West Virginia,South,24181,-80.6665,38.4204,3617,1.4,69.48,6.7,41.6,100,24070
48,WI,Wisconsin,North Central,56154,-89.9941,44.5937,4468,0.7,72.48,3.0,54.5,149,54464
49,WY,Wyoming,West,97914,-107.2560,43.0504,4566,0.6,70.29,6.9,62.9,173,97203

We can programmatically query shape details about a DataFrame. The shape property returns a 2-tuple containing the row and column counts for the DataFrame. The standard len function will return just the number of rows in the DataFrame.

In [4]:
statedat.shape

(50, 13)

In [5]:
len(statedat)

50

## What makes a DataFrame special

OK, so what's so special about a DataFrame? The Pandas dataframe is a powerhouse for managing and manipulating data. It's the Python standard and is expected input and output for many data science and machine learning libraries for Python. So, we *know* we need to learn to use this well. DataFrame *indexes* are one of those things that makes DataFrames special.

### Indexes

Pandas DataFrames actually have two sets of indexes:

- Row indexes - each row can be identified with a non-unique (but we *like* them to be unique) value
- Column indexes (refered to as column names) - each column is identified with a name.

What's so special about indexes? They allow us to access the specific contents of a DataFrame by index value. For example, we can easily *grab* the *name* column from the DataFrame:

In [6]:
statedat['name'].head()

0       Alabama
1        Alaska
2       Arizona
3      Arkansas
4    California
Name: name, dtype: object

Similarly, we can grab a row or rows using indexing (similar to Numpy indexing), including slices.

In [7]:
statedat[0:3]

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
0,AL,Alabama,South,51609,-86.7509,32.5901,3624,2.1,69.05,15.1,41.3,20,50708
1,AK,Alaska,West,589757,-127.2500,49.2500,6315,1.5,69.31,11.3,66.7,152,566432
2,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417

And, as you'd expect, we can be very specific with our subsetting. For example, we can obtain name, region, and income for rows 10-12 if that's all we're interested in:

In [8]:
statedat.loc[10:13,['name', 'region', 'income']]

        name         region  income
10    Hawaii           West    4963
11     Idaho           West    4119
12  Illinois  North Central    5107
13   Indiana  North Central    4458

To make the selection above, I used the DataFrames .loc method. When we just use square bracket indexing on the DataFrame instance, e.g. statedat['name'], Pandas expects the argument to be a column name or a list of column names *or* a row index or slice. When we want to select on both the row and column, we must use .loc or .iloc.

### .loc and .iloc

Pandas gives us the ability to access rows and columns using either the index values and column names *as well as* numeric subscripts. Our examples so far have used only the indexes and column names. By default, Pandas index values will be sequential numbers starting at 0. That's what we see in the statedat dataframe. Below, we can see the first few rows of the DataFrame, showing the index values at the left (unlabeled column at the left). We also show the complete index, obtained using the index attribute of the DataFrame.

In [9]:
statedat.head()

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
0,AL,Alabama,South,51609,-86.7509,32.5901,3624,2.1,69.05,15.1,41.3,20,50708
1,AK,Alaska,West,589757,-127.2500,49.2500,6315,1.5,69.31,11.3,66.7,152,566432
2,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417
3,AR,Arkansas,South,53104,-92.2992,34.7336,3378,1.9,70.66,10.1,39.9,65,51945
4,CA,California,West,158693,-119.7730,36.5341,5114,1.1,71.71,10.3,62.6,20,156361

In [10]:
print([i for i in statedat.index])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

But we can make the index (and column names) anything we want. Let's change the statedat index to use the state abbreviations:

In [11]:
statedat.index = statedat['abb']
statedat.head()

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
abb,,,,,,,,,,,,,
AL,AL,Alabama,South,51609,-86.7509,32.5901,3624,2.1,69.05,15.1,41.3,20,50708
AK,AK,Alaska,West,589757,-127.2500,49.2500,6315,1.5,69.31,11.3,66.7,152,566432
AZ,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417
AR,AR,Arkansas,South,53104,-92.2992,34.7336,3378,1.9,70.66,10.1,39.9,65,51945
CA,CA,California,West,158693,-119.7730,36.5341,5114,1.1,71.71,10.3,62.6,20,156361

Here we see that the leftmost column now contains the state abbreviations instead of the sequential numbers. Cool, right? It looks a little odd, because now our index and *abb* column contain the same information (we could always drop the abb column). But there's a real advantage to this. Previously, if we wanted to access the data for Oregon, we'd have to use the following:

In [12]:
statedat[statedat['abb'] == 'OR']

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
abb,,,,,,,,,,,,,
OR,OR,Oregon,West,96981,-120.068,43.9078,4660,0.6,72.13,4.2,60.0,44,96184

Now, we can use the 2-character state abbreviation as the subscript:

In [13]:
statedat.loc['OR']

abb                OR
name           Oregon
region           West
area            96981
center_x     -120.068
center_y      43.9078
income           4660
illiteracy        0.6
life_exp        72.13
murder            4.2
hs_grad          60.0
frost              44
area.1          96184
Name: OR, dtype: object

&nbsp;

We can even use a slice on the new index. **Note, however, that for *indexes*, unlike Python slices, Pandas *includes* the upper bound**:

In [14]:
statedat[:'CA']

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
abb,,,,,,,,,,,,,
AL,AL,Alabama,South,51609,-86.7509,32.5901,3624,2.1,69.05,15.1,41.3,20,50708
AK,AK,Alaska,West,589757,-127.2500,49.2500,6315,1.5,69.31,11.3,66.7,152,566432
AZ,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417
AR,AR,Arkansas,South,53104,-92.2992,34.7336,3378,1.9,70.66,10.1,39.9,65,51945
CA,CA,California,West,158693,-119.7730,36.5341,5114,1.1,71.71,10.3,62.6,20,156361

We can also use column slices and fancy indexes:

In [15]:
statedat.loc['AZ':'CA']

,abb,name,region,area,center_x,center_y,income,illiteracy,life_exp,murder,hs_grad,frost,area.1
abb,,,,,,,,,,,,,
AZ,AZ,Arizona,West,113909,-111.6250,34.2192,4530,1.8,70.55,7.8,58.1,15,113417
AR,AR,Arkansas,South,53104,-92.2992,34.7336,3378,1.9,70.66,10.1,39.9,65,51945
CA,CA,California,West,158693,-119.7730,36.5341,5114,1.1,71.71,10.3,62.6,20,156361

In [16]:
statedat[['abb', 'name', 'center_x', 'center_y']]

    abb            name  center_x  center_y
abb
AL   AL         Alabama  -86.7509   32.5901
AK   AK          Alaska -127.2500   49.2500
AZ   AZ         Arizona -111.6250   34.2192
AR   AR        Arkansas  -92.2992   34.7336
CA   CA      California -119.7730   36.5341
CO   CO        Colorado -105.5130   38.6777
CT   CT     Connecticut  -72.3573   41.5928
DE   DE        Delaware  -74.9841   38.6777
FL   FL         Florida  -81.6850   27.8744
GA   GA         Georgia  -83.3736   32.3329
HI   HI          Hawaii -126.2500   31.7500
ID   ID           Idaho -113.9300   43.5648
IL   IL        Illinois  -89.3776   40.0495
IN   IN         Indiana  -86.0808   40.0495
IA   IA            Iowa  -93.3714   41.9358
KS   KS          Kansas  -98.1156   38.4204
KY   KY        Kentucky  -84.7674   37.3915
LA   LA       Louisiana  -92.2724   30.6181
ME   ME           Maine  -68.9801   45.6226
MD   MD        Maryland  -76.6459   39.2778
MA   MA   Massachusetts  -71.5800   42.3645
MI   MI        Michigan  -84.6870   43.1361
MN   MN       Minnesota  -94.6043   46.3943
MS   MS     Mississippi  -89.8065   32.6758
MO   MO        Missouri  -92.5137   38.3347
MT   MT         Montana -109.3200   46.8230
NE   NE        Nebraska  -99.5898   41.3356
NV   NV          Nevada -116.8510   39.1063
NH   NH   New Hampshire  -71.3924   43.3934
NJ   NJ      New Jersey  -74.2336   39.9637
NM   NM      New Mexico -105.9420   34.4764
NY   NY        New York  -75.1449   43.1361
NC   NC  North Carolina  -78.4686   35.4195
ND   ND    North Dakota -100.0990   47.2517
OH   OH            Ohio  -82.5963   40.2210
OK   OK        Oklahoma  -97.1239   35.5053
OR   OR          Oregon -120.0680   43.9078
PA   PA    Pennsylvania  -77.4500   40.9069
RI   RI    Rhode Island  -71.1244   41.5928
SC   SC  South Carolina  -80.5056   33.6190
SD   SD    South Dakota  -99.7238   44.3365
TN   TN       Tennessee  -86.4560   35.6767
TX   TX           Texas  -98.7857   31.3897
UT   UT            Utah -111.3300   39.1063
VT   VT         Vermont  -72.5450   44.2508
VA   VA        Virginia  -78.2005   37.5630
WA   WA      Washington -119.7460   47.4231
WV   WV   West Virginia  -80.6665   38.4204
WI   WI       Wisconsin  -89.9941   44.5937
WY   WY         Wyoming -107.2560   43.0504

In [17]:
statedat.iloc[11:21, 3:6]

      area  center_x  center_y
abb
ID   83557 -113.9300   43.5648
IL   56400  -89.3776   40.0495
IN   36291  -86.0808   40.0495
IA   56290  -93.3714   41.9358
KS   82264  -98.1156   38.4204
KY   40395  -84.7674   37.3915
LA   48523  -92.2724   30.6181
ME   33215  -68.9801   45.6226
MD   10577  -76.6459   39.2778
MA    8257  -71.5800   42.3645

In this case, we used the .iloc property to access rows and columns by position number. **Note that here, when using position number indexing, Pandas follows Python's convention that the upper bound is *excluded* from the result.**

## Pandas Series

If we think of a DataFrame as consisting of a collection of columns of equal length, then we have a good picture of how a DataFrame is implemented. Specifically, a DataFrame consists of a collection of Pandas Series objects, where a Series object is very similar to a Numpy Ndarray. Series behave like numpy arrays in many (most?) respects. However, like DataFrames, Series objects have indexes (but not column names since they are one-dimensional).

We can observe this by extracting a column from our DataFrame and observing its type:

In [18]:
type(statedat['abb'])

pandas.core.series.Series

OK, that wasn't very exciting, but it proved the point. Pandas DataFrame columns are Series. No, what else can we learn about a Series object?

In [19]:
statedat['name'].head()

abb
AL       Alabama
AK        Alaska
AZ       Arizona
AR      Arkansas
CA    California
Name: name, dtype: object

If we look at the first few values in the Series, we'll see that the *extracted* Series object retains the indexes from the DataFrame. Here we see that we can access Series elements by index and by position:

In [20]:
statedat['name']['OR']

'Oregon'

In [21]:
statedat['name'][10]

'Hawaii'

As with DataFrames, positional slices *exclude* the upper bound

In [22]:
statedat['name'][0:5]

abb
AL       Alabama
AK        Alaska
AZ       Arizona
AR      Arkansas
CA    California
Name: name, dtype: object

but index slices *include* the upper bound

In [23]:
statedat['name'][:'CA']

abb
AL       Alabama
AK        Alaska
AZ       Arizona
AR      Arkansas
CA    California
Name: name, dtype: object

Series objects can be created similarly to Numpy arrays (e.g. using a list)

In [24]:
new_obj = pd.Series(['apple', 'pear', 'watermelon', 'strawberries'])
new_obj

0           apple
1            pear
2      watermelon
3    strawberries
dtype: object

Notice that the index here consists of sequential integers. This represents the default because no index values were supplied. Alternatively, we can supply an index when we create the Series:

In [25]:
new_obj = pd.Series(['apple', 'pear', 'watermelon', 'strawberries'],
                    index=['a', 'p', 'w', 's'])
new_obj

a           apple
p            pear
w      watermelon
s    strawberries
dtype: object

A nice neat way to construct a Series is using a Python dictionary; the dictionary keys will be used as index values and the dictionary values will be the Series values:

In [26]:
new_obj = pd.Series({'a': 'apple', 'p':'pear', 'w':'watermelon', 's':'strawberries'})
new_obj

a           apple
p            pear
w      watermelon
s    strawberries
dtype: object

As with DataFrames, Series objects are very flexible and provide a large number of methods for manipulating the Series.

## Constructing DataFrames

So, how do we create a DataFrame? We already saw one easy method, creating a DataFrame from a .csv file. Alternatively, we can create DataFrames using:

- Lists of lists (each inner list represents a row in the DataFrame)
- Dictionary of lists, specifying column names and/or index values
- Dictionary of Series (each series represents a column in the DataFrame).

### List of lists

In [27]:
df1 = pd.DataFrame([['AK', 'Alaska'],
                    ['AL', 'Alabama'],
                    ['AR', 'Arkansas'],
                    ['AZ', 'Arizona'],
                    ['CA', 'California']
                   ])
df1

    0           1
0  AK      Alaska
1  AL     Alabama
2  AR    Arkansas
3  AZ     Arizona
4  CA  California

Note in the result above that the row and column indexes are, by default,  sequential integers.

### Lists of lists specifying column and/or row labels

In [28]:
df1 = df1 = pd.DataFrame([['AK', 'Alaska'],
                    ['AL', 'Alabama'],
                    ['AR', 'Arkansas'],
                    ['AZ', 'Arizona'],
                    ['CA', 'California']
                   ], columns=['Abb', 'Name'])
df1

  Abb        Name
0  AK      Alaska
1  AL     Alabama
2  AR    Arkansas
3  AZ     Arizona
4  CA  California

In [29]:
df1 = df1 = pd.DataFrame([['AK', 'Alaska'],
                    ['AL', 'Alabama'],
                    ['AR', 'Arkansas'],
                    ['AZ', 'Arizona'],
                    ['CA', 'California']
                   ], index=['K', 'L', 'R', 'Z', 'A'])
df1

    0           1
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California

In [30]:
df1 = df1 = pd.DataFrame([['AK', 'Alaska'],
                    ['AL', 'Alabama'],
                    ['AR', 'Arkansas'],
                    ['AZ', 'Arizona'],
                    ['CA', 'California']
                   ], columns=['Abb', 'Name'],
                      index=['K', 'L', 'R', 'Z', 'A'])
df1

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California

### Dictionary of Series

Here, the dictionary keys become the column labels. The row labels are drawn from the Series indexes.

In [31]:
abbs = pd.Series(['AK', 'AL', 'AR', 'AZ', 'CA'])
names = pd.Series(['Alaska', 'Alabama', 'Arkansas', 'Arizona', 'California'])

pd.DataFrame({'Abb': abbs, 'Name': names})

  Abb        Name
0  AK      Alaska
1  AL     Alabama
2  AR    Arkansas
3  AZ     Arizona
4  CA  California

When constructing a DataFrame from Series objects, Pandas *matches* the Series elements using the indexes. In the example below, we construct the two Series objects with *different* indexes. The abbs Series is indexed 0 through 4, whereas the names indexes are 6-10.

In [32]:
abbs = pd.Series(['AK', 'AL', 'AR', 'AZ', 'CA'], index=range(5))
names = pd.Series(['Alaska', 'Alabama', 'Arkansas', 'Arizona', 'California'], index=range(6,11))

pd.DataFrame({'Abb': abbs, 'Name': names})

    Abb        Name
0    AK         NaN
1    AL         NaN
2    AR         NaN
3    AZ         NaN
4    CA         NaN
6   NaN      Alaska
7   NaN     Alabama
8   NaN    Arkansas
9   NaN     Arizona
10  NaN  California

In this result, note the following:
- There is no element 5. Even though the indexes are numbers, they are not necessarily sequential
- There are 10 rows in the DataFrame (rather than 5 previously). The first 5 rows were constructed with the abbs data (they had the lowest index values) while the last 5 were derived from the names
- There are *missing values* for Name in the first 5 rows and for Abb in the last 5 rows.

When constructing this DataFrame, Pandas matched up the two Series objects on the Indexes, with the data associated with each index *merged* to create a row in the resulting DataFrame. Because the first 5 rows had no matching index in the names Series, the Name column values are all set to NaN (and similarly with the Abb values in the last 5 columns).

## Missing values as NaNs

Pandas' treatment of missing values is one of its idiosyncrasies. Most tools that explicitly handle missing values identify them separately from infinity and not a number (Nan). The Pandas designers made an implementation decision to use NaN to represent both missing values and traditional NaN values. This allowed them to streamline their handling of numeric columns, but it *is* something to keep in miind when designing your applications.

### Eliminating missing values

The .dropna DataFrame method can be used to drop missing values from DataFrames. It provides very flexible usage, so you should definitely read the documentation to get a sense of its range of capabilities. The simplest usage (and the frequently desired behavior), is simply to drop all rows where a missing value exists for any column (the rationale being that the observation is incomplete):

In [33]:
dfna = df1
dfna.loc['R','Name'] = pd.NA
dfna

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR        <NA>
Z  AZ     Arizona
A  CA  California

In [34]:
dfna.dropna()

  Abb        Name
K  AK      Alaska
L  AL     Alabama
Z  AZ     Arizona
A  CA  California

.dropna() returns an altered DataFrame. But be careful here, by default, .dropna() **does not alter the original DataFrame**.

In [35]:
dfna

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR        <NA>
Z  AZ     Arizona
A  CA  California

The output above shows that the original DataFrame, dfna, was *not* altered by the .dropna() call. This is not a mistake. This allows you to make a copy of a DataFrame that excludes the missing values contained in the original. Just assign the .dropna() result to a new variable. There *are* situations, however, when creating this copy can be quite time-consuming (and memory intensive). In these cases, there's an *inplace* argument in the .dropna() call that you can use to instruct Pandas to alter the original DataFrame rather than producing a new one (see the Pandas .dropna() documentation).

There are a number of other useful methods relating to missing values in DataFrames (see the Pandas doc for descriptions):

- isna
- notna
- fillna

## Adding to or modifying an Existing DataFrame

DataFrames are mutable. We can modify data in a DataFrame, just as you would expect:

In [36]:
dfna.loc['R', 'Name'] = 'Arkansas'
dfna

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California

We can also delete rows from a DataFrame. Here we delete a row using index values (or column names). When we invoke drop, it *assumes* the index values provided in the call correspond to row index values (unless we tell it otherwise).

In [39]:
dfna.drop('R')

  Abb        Name
K  AK      Alaska
L  AL     Alabama
Z  AZ     Arizona
A  CA  California

Note that, as with .dropna(), .drop() returns a new DataFrame with the changes, rather than updating the current object (unless the inplace=True argument is specified). In the example below, we specify *axis=1* to tell Pandas to drop a column to drop (axis=0, the default, specifies row deletion). This works fine, but I don't really like this version. It's too cryptic.

In [41]:
dfna.drop('Abb', axis=1)

         Name
K      Alaska
L     Alabama
R    Arkansas
Z     Arizona
A  California

I prefer the following alternative for specifying column deletion.

In [42]:
dfna.drop(columns='Abb')

         Name
K      Alaska
L     Alabama
R    Arkansas
Z     Arizona
A  California

We can also delete rows that satisfy a condition (*all* rows satisfying the condition):

In [43]:
dfna.drop(dfna[dfna['Abb'] == 'AZ'].index)

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
A  CA  California

The code above bears explanation. Executing from the inside out will illustrate. The innermost code extracts the rows that satisfy the condition. .drop() won't know how to operate on this, because it expects a set of index values to tell it which rows to drop.

In [44]:
dfna[dfna['Abb'] == 'AZ']

  Abb     Name
Z  AZ  Arizona

So, we add .index to the DataFrame subset; .index will return the index values for the subset.

In [45]:
dfna[dfna['Abb'] == 'AZ'].index

Index(['Z'], dtype='object')

Here's another example showing the indexes matching the condition that the abbreviation $\le$ 'A'

In [47]:
dfna[dfna['Abb'] <= 'Aa'].index

Index(['K', 'L', 'R', 'Z'], dtype='object')

So why did $\le$ 'Aa' return the indexes for the first four rows? Because, to a computer 'Z' $<$ 'a'. In other words, upper case letters have a lower sort value than lower case letters. Ultimately, we see that .drop() is *always* using index values for dropping the rows, but we have a variety of ways that we can obtain those indexes.

In [ ]:
dfna.drop(dfna[dfna['Abb'] == 'AZ'].index)

## Adding Columns and Rows to DataFrames
Adding data to DataFrames is *relatively* easy (there are occasionally tricky exceptions). To illustrate, let's start by adding Oregon to our DataFrame. We'll use the .loc proprty to let Pandas know that we're adding a row via an index. Note that an easy way to supply the values is as a dictionary; using a dictionary for the new data allows the new data to appear in any order

In [51]:
df2 = df1.copy()
df2.loc['O'] = {'Name': 'Oregon', 'Abb': 'OR'}
df2

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California
O  OR      Oregon

Alternatively, we could supply the new data, in column order:

In [53]:
df2.loc['W'] = ['WA', 'Washington']
df2

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California
O  OR      Oregon
W  WA  Washington

We could also add multiple rows at once, but we'll have to use .concat; .loc and .iloc can be used to add a single row, but not multiple rows at once. The benefit of using .loc (or .iloc) is that the current DataFrame is updated.

In [77]:
df2 = df1.copy()

# construct DataFrane with new rows and set indexes
new_df = pd.DataFrame({'Abb': pd.Series(['ID', 'MT']), 'Name': pd.Series(['Idaho', 'Montana'])})
new_df.index = ['I', 'M']

# Now, concatenate the DataFrames
combined = pd.concat([df2, new_df])
combined

  Abb        Name
K  AK      Alaska
L  AL     Alabama
R  AR    Arkansas
Z  AZ     Arizona
A  CA  California
I  ID       Idaho
M  MT     Montana

The Pandas .concat() function (it's a function, not an instance method) returns a new DataFrame. Using .concat() is easy (line 8 above) when you are trying to append one DataFrame to another. The first argument to .concat() is a list of the Pandas objects you wish to concatenate. This allows you to concatenate as many different Pandas objects as you like.

If your new data is not already in a DataFrame, it's probably easiest to construct a new DataFrame with the new data rather than using other approaches. The .concat() method is very flexible and can be used to add both rows and columns to DataFrame. You should review the .concat() documentation for more details, there's a lot there.

## .join() and .merge()

The .join() and .merge() methods (of DataFrame) allow you to combine DataFrames in a method analogous to SQL joins and merges. For example, we can add a new column indicating whether or note a state has a coastline:

In [84]:
coastal = pd.Series([True, True, False, False, True], index=['AK', 'AL', 'AR', 'AZ', 'CA'], name='Coastal')
df1.join(coastal, on='Abb')

  Abb        Name  Coastal
K  AK      Alaska     True
L  AL     Alabama     True
R  AR    Arkansas    False
Z  AZ     Arizona    False
A  CA  California     True

This is really nice! Pandas will match up the rows using the *index* values of the argument and either the index values of the original DataFrame or, as in this example, the values in a column (specified using the *on* argument). Note that the *name* property of the Series is used as the column name in the joined DataFrame.

Similarly, we can use merge. However, *merge* gives us even more flexibility in how Pandas will match the rows in the inputs; we can use either columns or indexes for the merge keys in both the *left* and *right* DataFrames (the left DataFrame is the object used to invoke the .merge method).

In [86]:
coastal = pd.Series([True, True, False, False, True], index=['AK', 'AL', 'AR', 'AZ', 'CA'], name='Coastal')
df1.merge(coastal, left_on='Abb', right_index=True)

  Abb        Name  Coastal
K  AK      Alaska     True
L  AL     Alabama     True
R  AR    Arkansas    False
Z  AZ     Arizona    False
A  CA  California     True

## More to Learn
There is much more to learn about manipulating Pandas DataFrames, but there's no substitute for *playing* with them. You can use the data in the statedat.csv file or you can create your own DataFrames. In fact, you should practice doing *both*.

For more information, see [Pandas DataFrames](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) and [Pandas Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).